networks:
  krekbots-network:
    name: krekbots-network
    driver: bridge

services:
  postgres:
    image: postgres:17
    networks: 
      - krekbots-network
    container_name: krekbots-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
      - ./postgres/backups:/docker-entrypoint-backups:ro
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  krekbot-economy:
    build: ./economy-bot
    image: hypoxie/krekbot-economy
    container_name: krekbot-economy
    restart: always
    networks:
      - krekbots-network
    env_file:
      - .env
      - secrets.priv
    depends_on:
      postgres:
        condition: service_healthy

  krekbot-moderation:
    build: ./moderation-bot
    image: hypoxie/krekbot-moderation
    container_name: krekbot-moderation
    restart: always
    networks:
      - krekbots-network
    env_file:
      - .env
      - secrets.priv
    depends_on:
      postgres:
        condition: service_healthy

  v2raya:
     image: mzz2017/v2raya:v2.2.7.5
     container_name: v2raya
     restart: always
     networks:
       - krekbots-network
     ports:
       - "2017:2017"
     environment:
       - V2RAYA_ADDRESS=0.0.0.0:2017
     volumes:
       - ./v2raya_data:/etc/v2raya

  curl:
    image: curlimages/curl:8.20.0
    container_name: curl
    networks:
      - krekbots-network
    environment:
      - http_proxy=http://v2raya:20171
      - https_proxy=http://v2raya:20171
      - no_proxy=postgres,db,redis,localhost,127.0.0.1,.local
      - SOCKS5_PROXY=socks5://v2raya:20170
      - HTTP_PROXY=http://v2raya:20171
      - HTTPS_PROXY=http://v2raya:20171
      - NO_PROXY=postgres,db,redis,localhost,127.0.0.1,.local
    command: ["sleep", "infinity"]