networks:
  krekbots-network:
    name: krekbots-network
    driver: bridge

services:
  postgres:
    image: postgres:17
    networks: 
      - krekbots-network
    container_name: krekbots-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
      - ./postgres/backups:/docker-entrypoint-backups:ro
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  krekbot-economy:
    build: ./economy-bot
    image: hypoxie/krekbot-economy
    container_name: krekbot-economy
    restart: always
    networks:
      - krekbots-network
    env_file:
      - .env
      - secrets.priv
    depends_on:
      postgres:
        condition: service_healthy

  krekbot-moderation:
    build: ./moderation-bot
    image: hypoxie/krekbot-moderation
    container_name: krekbot-moderation
    restart: always
    networks:
      - krekbots-network
    env_file:
      - .env
      - secrets.priv
    depends_on:
      postgres:
        condition: service_healthy

  s-ui:
    image: ghcr.io/alireza0/s-ui:latest
    container_name: krekbots_s-ui
    restart: always
    networks:
      - krekbots-network
    ports:
      - "8000:2095"
    volumes:
      - ./s-ui_data:/app/db


  # curl:
  #   image: curlimages/curl:8.20.0
  #   container_name: curl
  #   networks:
  #     - krekbots-network
  #   environment:
  #     - http_proxy=http://krekbots_s-ui:20170
  #     - https_proxy=http://krekbots_s-ui:20170
  #     - no_proxy=postgres,db,redis,localhost,127.0.0.1,.local
  #     - SOCKS5_PROXY=socks5://krekbots_s-ui:20170
  #     - HTTP_PROXY=http://krekbots_s-ui:20170
  #     - HTTPS_PROXY=http://krekbots_s-ui:20170
  #     - NO_PROXY=postgres,db,redis,localhost,127.0.0.1,.local
  #   command: ["sleep", "infinity"]

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: krekbot-pgadmin4
  #   restart: unless-stopped
  #   networks: 
  #     - krekbots-network
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   user: "0:0"
  #   ports:
  #     - "8001:80"
  #   volumes:
  #     - ./pgadmin_data:/var/lib/pgadmin
