networks:
  postgres-network:
    name: postgres-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    attachable: true

services:
  postgres:
    image: postgres:17
    networks: 
      - postgres-network
    container_name: shared-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./backups:/docker-entrypoint-backups:ro
      - ./init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped